### ISSUE TITLE
Can't access the web UI

### ISSUE THREAD

**Issue by Tummolo** [Gradiant/openverso-images#203]
Hi, 
I cloned the repo and just run the compose command: 
`docker-compose -f ngc.yaml up -d`
Then, when trying to access the web UI via the address 0.0.0.0:3000 I get the following error, which I retrieved using `docker logs -f open5gs-and-ueransim_webui_1`:
```
ubuntu@gateway:~/openverso-images/docs/open5gs-and-ueransim$ docker logs -f open5gs-and-ueransim_webui_1
> Ready on http://0.0.0.0:3000
Unhandled rejection MongoError: Unsupported OP_QUERY command: listIndexes. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal
    at Function.MongoError.create (/opt/open5gs-webui/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/opt/open5gs-webui/node_modules/mongoose/node_modules/mongodb-core/lib/cursor.js:212:36)
    at /opt/open5gs-webui/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Comment by avrodriguezgrad** [comment]
Try to update the version (2.3.2 -> 2.6.4) used in the docker-compose and tell us if that fixes your problem.

BR,
Álvaro
